SELECT B.COORDINADOR, A.NOMBRE_TEMA 
FROM tbl_temas A
INNER JOIN (
  SELECT ROWNUM AS CODIGO_COORDINADOR, ALEATORIO, COORDINADOR
  FROM (
    SELECT ROUND(DBMS_RANDOM.VALUE(1,1000)) AS aleatorio,
          coordinador
    FROM tbl_coordinadores
    ORDER BY aleatorio
  )
) B
ON (A.CODIGO_TEMA = B.CODIGO_COORDINADOR);