SET SERVEROUTPUT ON;

--cursor explicito utilizando loop
DECLARE
  CURSOR C_EMPLEADOS IS SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;
  V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
  V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
  OPEN C_EMPLEADOS;
  LOOP  
    FETCH C_EMPLEADOS INTO V_FIRST_NAME, V_LAST_NAME;
    EXIT WHEN C_EMPLEADOS%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('NOMRE: '||V_FIRST_NAME || ' ' || V_LAST_NAME);
  END LOOP;
  CLOSE C_EMPLEADOS;
END;

--cursor explicito utilizando loop y rowtype
DECLARE
  CURSOR C_EMPLEADOS IS SELECT * FROM EMPLOYEES;
  V_REGISTRO EMPLOYEES%ROWTYPE;
BEGIN
  OPEN C_EMPLEADOS;
  LOOP  
    FETCH C_EMPLEADOS INTO V_REGISTRO;
    EXIT WHEN C_EMPLEADOS%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('NOMRE: '||V_REGISTRO.FIRST_NAME || 
    ' ' || V_REGISTRO.LAST_NAME || '-' ||V_REGISTRO.SALARY );
  END LOOP;
  CLOSE C_EMPLEADOS;
END;

--Cursor explicito utilizando for
DECLARE
  CURSOR C_EMPLEADOS IS SELECT * FROM EMPLOYEES;
BEGIN
  FOR V_REGISTRO IN C_EMPLEADOS LOOP  
    DBMS_OUTPUT.PUT_LINE('NOMRE: '||V_REGISTRO.FIRST_NAME || 
    ' ' || V_REGISTRO.LAST_NAME || '-' ||V_REGISTRO.SALARY );
  END LOOP;
END;

--cursor implicito: sin nombre
BEGIN
  FOR V_REGISTRO IN (SELECT * FROM EMPLOYEES) LOOP  
    DBMS_OUTPUT.PUT_LINE('NOMRE: '||V_REGISTRO.FIRST_NAME || 
    ' ' || V_REGISTRO.LAST_NAME || '-' ||V_REGISTRO.SALARY );
  END LOOP;
END;



DECLARE
  V_NOMBRE_TABLA VARCHAR2(500):='REGIONS_BACKUP_'||TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS');
  V_SQL VARCHAR2(1000):='CREATE TABLE ' || V_NOMBRE_TABLA ||
      '(REGION_ID NUMBER, REGION_NAME VARCHAR2(25))';
  
BEGIN
  DBMS_OUTPUT.PUT_LINE('CREAR TABLA, SE EJECURA EL SIGUIENTE SCRIPT: ');
  DBMS_OUTPUT.PUT_LINE(V_SQL);
  --CREAR LA TABLA
  EXECUTE IMMEDIATE V_SQL;
  
  FOR V_REGISTRO IN (SELECT * FROM REGIONS) LOOP
    EXECUTE IMMEDIATE 'INSERT INTO ' || 
        V_NOMBRE_TABLA || '(REGION_ID, REGION_NAME) VALUES ('||
          V_REGISTRO.REGION_ID||','||
          ''''||V_REGISTRO.REGION_NAME||''')';
  END LOOP;
END;



SELECT * FROM REGIONS_BACKUP_20151026105828;


CREATE TABLE NOMBRE_TABLA AS
SELECT * FROM REGIONS;

SELECT * FROM NOMBRE_TABLA;
