CREATE OR REPLACE TRIGGER TRG_REPLICAR_EMPLEADO
AFTER INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
  INSERT INTO EMPLOYEES_BACKUP
  (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
  )
  VALUES
  (
    :NEW.EMPLOYEE_ID,
    :NEW.FIRST_NAME,
    :NEW.LAST_NAME,
    :NEW.EMAIL,
    :NEW.PHONE_NUMBER,
    :NEW.HIRE_DATE,
    :NEW.JOB_ID,
    :NEW.SALARY,
    :NEW.COMMISSION_PCT,
    :NEW.MANAGER_ID,
    :NEW.DEPARTMENT_ID
  );
  COMMIT;
EXCEPTION  
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM||SQLCODE);
END;


INSERT
INTO EMPLOYEES
  (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
  )
  VALUES
  (
    600,
    'MATUSALEN',
    'RODRIGUEZ',
    'matu@gmail.com',
    '123.123.123',
    sysdate,
    'PU_MAN',
    40000,
    0.4,
    100,
    20
);
COMMIT;