--Creacion de una funcion
CREATE OR REPLACE FUNCTION F_CANTIDAD_EMPLEADOS 
RETURN INTEGER AS
  V_CANTIDAD_EMPLEADOS INTEGER;
BEGIN
  SELECT COUNT(1)
  INTO V_CANTIDAD_EMPLEADOS
  FROM EMPLOYEES;

  RETURN V_CANTIDAD_EMPLEADOS;
END;

--Llamar la funcion desde un select
SELECT F_CANTIDAD_EMPLEADOS() AS CANTIDAD_EMPLEADOS
FROM DUAL;

set serveroutput on;

BEGIN
  DBMS_OUTPUT.PUT_LINE('Cantidad Empleados: '||F_CANTIDAD_EMPLEADOS());
END;

SELECT *
FROM EMPLOYEES;




---
CREATE OR REPLACE PACKAGE PKG_EMPLOYEES AS
  PROCEDURE SP_INSERTAR(
      P_FIRST_NAME VARCHAR2,
      P_LAST_NAME VARCHAR2,
      P_EMAIL VARCHAR2,
      P_PHONE_NUMBER VARCHAR2,
      P_HIRE_DATE DATE,
      P_JOB_ID INTEGER,
      P_SALARY NUMBER,
      P_COMMISSION_PCT NUMBER,
      P_MANAGER_ID INTEGER,
      P_DEPARTMENT_ID INTEGER,
      P_EMPLOYEE_ID OUT INTEGER,
      P_RESULTADO OUT VARCHAR2
  );
  PROCEDURE SP_ACTUALIZAR(
      P_EMPLOYEE_ID INTEGER,
      P_FIRST_NAME VARCHAR2,
      P_LAST_NAME VARCHAR2,
      P_EMAIL VARCHAR2,
      P_PHONE_NUMBER VARCHAR2,
      P_HIRE_DATE DATE,
      P_JOB_ID INTEGER,
      P_SALARY NUMBER,
      P_COMMISSION_PCT NUMBER,
      P_MANAGER_ID INTEGER,
      P_DEPARTMENT_ID INTEGER,
      P_RESULTADO OUT VARCHAR2
  );
  PROCEDURE SP_ELIMINAR(
    P_EMPLOYEE_ID INTEGER,
    P_RESULTADO OUT VARCHAR2
  );
END;


--DEFINICION DEL CUERPO
CREATE OR REPLACE PACKAGE BODY PKG_EMPLOYEES AS
  PROCEDURE SP_INSERTAR(
      P_FIRST_NAME VARCHAR2,
      P_LAST_NAME VARCHAR2,
      P_EMAIL VARCHAR2,
      P_PHONE_NUMBER VARCHAR2,
      P_HIRE_DATE DATE,
      P_JOB_ID INTEGER,
      P_SALARY NUMBER,
      P_COMMISSION_PCT NUMBER,
      P_MANAGER_ID INTEGER,
      P_DEPARTMENT_ID INTEGER,
      P_EMPLOYEE_ID OUT INTEGER,
      P_RESULTADO OUT VARCHAR2
  ) AS
  BEGIN
    P_RESULTADO :='INICIANDO INSERCION';
    INSERT INTO EMPLOYEES(
      EMPLOYEE_ID,
      FIRST_NAME,
      LAST_NAME,
      EMAIL,
      PHONE_NUMBER,
      HIRE_DATE,
      JOB_ID,
      SALARY,
      COMMISSION_PCT,
      MANAGER_ID,
      DEPARTMENT_ID
    )
    VALUES
    (
      P_EMPLOYEE_ID,
      P_FIRST_NAME,
      P_LAST_NAME,
      P_EMAIL,
      P_PHONE_NUMBER,
      P_HIRE_DATE,
      P_JOB_ID,
      P_SALARY,
      P_COMMISSION_PCT,
      P_MANAGER_ID,
      P_DEPARTMENT_ID
    );
    
    COMMIT;
    P_RESULTADO := 'TRANSACCION EXITOSA';
  EXCEPTION 
    WHEN OTHERS THEN 
      P_RESULTADO := 'ERROR, '||SQLERRM||'-'||SQLCODE;
      ROLLBACK;
      --DBMS_OUTPUT.PUT_LINE(P_RESULTADO);
  END;
  PROCEDURE SP_ACTUALIZAR(
      P_EMPLOYEE_ID INTEGER,
      P_FIRST_NAME VARCHAR2,
      P_LAST_NAME VARCHAR2,
      P_EMAIL VARCHAR2,
      P_PHONE_NUMBER VARCHAR2,
      P_HIRE_DATE DATE,
      P_JOB_ID INTEGER,
      P_SALARY NUMBER,
      P_COMMISSION_PCT NUMBER,
      P_MANAGER_ID INTEGER,
      P_DEPARTMENT_ID INTEGER,
      P_RESULTADO OUT VARCHAR2
  ) AS
  BEGIN
    UPDATE EMPLOYEES
    SET FIRST_NAME     = P_FIRST_NAME,
        LAST_NAME      = P_LAST_NAME,
        EMAIL          = P_EMAIL,
        PHONE_NUMBER   = P_PHONE_NUMBER,
        HIRE_DATE      = P_HIRE_DATE,
        JOB_ID         = P_JOB_ID,
        SALARY         = P_SALARY,
        COMMISSION_PCT = P_COMMISSION_PCT,
        MANAGER_ID     = P_MANAGER_ID,
        DEPARTMENT_ID  = P_DEPARTMENT_ID
    WHERE EMPLOYEE_ID  = P_EMPLOYEE_ID;
    COMMIT;
    P_RESULTADO := 'TRANSACCION EXITOSA';
  EXCEPTION 
    WHEN OTHERS THEN 
      P_RESULTADO := 'ERROR, '||SQLERRM||'-'||SQLCODE;
      ROLLBACK;
      --DBMS_OUTPUT.PUT_LINE(P_RESULTADO);
  END;
  
  PROCEDURE SP_ELIMINAR(
    P_EMPLOYEE_ID INTEGER,
    P_RESULTADO OUT VARCHAR2
  ) AS
  BEGIN
    DELETE
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID  = P_EMPLOYEE_ID;
    COMMIT;
    P_RESULTADO := 'TRANSACCION EXITOSA';
  EXCEPTION 
    WHEN OTHERS THEN 
      P_RESULTADO := 'ERROR, '||SQLERRM||'-'||SQLCODE;
      ROLLBACK;
  END;
END;


DECLARE
  V_EMPLOYEE_ID INTEGER:=500;
  V_RESULTADO VARCHAR2(2000);
BEGIN
  PKG_EMPLOYEES.SP_INSERTAR(
      P_FIRST_NAME=>'JUAN',
      P_LAST_NAME=>'PEREZ',
      P_EMAIL=>'juan@gmail.com  ',
      P_PHONE_NUMBER=>'555',
      P_HIRE_DATE=>SYSDATE,
      P_JOB_ID=>'SA_MAN',
      P_SALARY=>5400,
      P_COMMISSION_PCT=>0.4,
      P_MANAGER_ID=>107,
      P_DEPARTMENT_ID=>80,
      P_EMPLOYEE_ID=>V_EMPLOYEE_ID,
      P_RESULTADO=>V_RESULTADO
  );
  DBMS_OUTPUT.PUT_LINE(V_RESULTADO);
END;

SELECT *
FROM EMPLOYEES;





