drop PUBLIC DATABASE LINK DBLINK_LINUX;
CREATE PUBLIC DATABASE LINK DBLINK_LINUX
   CONNECT TO "AEROLINEA" IDENTIFIED BY  "oracle"
   USING 'REMOTE_LINUX_XE';


SELECT *
FROM DUAL@DBLINK_LINUX;

select *
from hr.employees@dblink_linux;

SELECT *
FROM AEROLINEA.TBL_AVIONES@DBLINK_LINUX;

CREATE OR REPLACE PROCEDURE SP_EX_AVIONES AS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    --LOG DE INICIO DE EJECUCION 
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TBL_AVIONES';
    INSERT INTO TBL_AVIONES (
      CODIGO_AVION, REGISTRO,
      CANTIDAD_ASIENTOS, NOMBRE_MARCA,
      NOMBRE_MODELO
    )
    SELECT A.CODIGO_AVION, A.REGISTRO,
        A.CANTIDAD_ASIENTOS, B.NOMBRE_MARCA,
        C.NOMBRE_MODELO
    FROM AEROLINEA.TBL_AVIONES@DBLINK_LINUX A
    INNER JOIN AEROLINEA.TBL_MARCAS@DBLINK_LINUX B
    ON (A.CODIGO_MARCA = B.CODIGO_MARCA)
    INNER JOIN AEROLINEA.TBL_MODELOS@DBLINK_LINUX C
    ON (A.CODIGO_MODELO = C.CODIGO_MODELO);
    --LOG DE FIN DE EJECUCION     
    COMMIT;
EXCEPTION 
  WHEN OTHERS THEN 
    DBMS_OUTPUT.PUT_LINE('ERROR AL EXTRAER LA INFORMACION'||SQLERRM);
    ROLLBACK;
    --LOG DE FIN DE EJECUCION 
END;

EXECUTE SP_EX_AVIONES;
