create or replace PROCEDURE SP_EX_FACTURAS AS 
  V_FECHA_INICIO DATE;
  V_FECHA_FIN DATE;
BEGIN
  /*SELECT MIN(FECHA)
  INTO V_FECHA_INICIO
  FROM AEROLINEA.TBL_FACTURAS@dblink_linux;

  SELECT NVL(MAX(FECHA),V_FECHA_INICIO)
  INTO V_FECHA_INICIO
  FROM TBL_FACTURAS;*/
  
  SELECT MAX(FECHA)
  INTO V_FECHA_INICIO
  FROM TBL_FACTURAS;
  
  IF (V_FECHA_INICIO IS NULL) THEN
      SELECT MIN(FECHA)
      INTO V_FECHA_INICIO
      FROM AEROLINEA.TBL_FACTURAS@dblink_linux; 
  END IF;
  
  V_FECHA_FIN := SYSDATE - 1;
  DBMS_OUTPUT.PUT_LINE('EXTRAER DESDE '||V_FECHA_INICIO||
  ' HASTA '||V_FECHA_FIN);
  WHILE (V_FECHA_INICIO<=V_FECHA_FIN) LOOP
    INSERT INTO TBL_FACTURAS(
      CODIGO_FACTURA,
      COSTO_TOTAL,
      TOTAL_IMPUESTOS,
      FECHA,
      FACTURADO
    )
    SELECT CODIGO_FACTURA,
        COSTO_TOTAL,
        TOTAL_IMPUESTOS,
        FECHA,
        FACTURADO
    FROM TBL_FACTURAS@DBLINK_LINUX
    WHERE TRUNC(FECHA) = TRUNC(V_FECHA_INICIO);
    
    DBMS_OUTPUT.PUT_LINE('EXTRACCION PARA LA FECHA '||
        V_FECHA_INICIO||' CANTIDAD_REGISTROS:'||SQL%ROWCOUNT);
    COMMIT;
    V_FECHA_INICIO:= V_FECHA_INICIO + 1;    
  END LOOP;
  
  DBMS_OUTPUT.PUT_LINE('EXTRACCION FINALIZADA');
EXCEPTION
WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR'||SQLERRM||'FECHA ERROR: '||V_FECHA_INICIO);
    ROLLBACK;
END;


SET SERVEROUTPUT ON;
TRUNCATE TABLE TBL_FACTURAS;

BEGIN
  SP_EX_FACTURAS;
END;


SELECT COUNT(1)
FROM TBL_FACTURAS;
--WHERE FECHA BETWEEN V_FECHA_INICIO AND V_FECHA_FIN;
SELECT COUNT(1)
FROM TBL_FACTURAS@DBLINK_LINUX;
--WHERE FECHA BETWEEN V_FECHA_INICIO AND V_FECHA_FIN;

SELECT SUM((COSTO_TOTAL + TOTAL_IMPUESTOS)) MONTO
FROM TBL_FACTURAS;
--WHERE FECHA BETWEEN V_FECHA_INICIO AND V_FECHA_FIN;
SELECT SUM((COSTO_TOTAL + TOTAL_IMPUESTOS)) MONTO
FROM TBL_FACTURAS@DBLINK_LINUX;
--WHERE FECHA BETWEEN V_FECHA_INICIO AND V_FECHA_FIN;
