SET SERVEROUTPUT ON;

BEGIN
  FOR V_Contador IN REVERSE 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE('CONTADOR: '||V_CONTADOR);
  END LOOP;
END;

--EN UN CICLO EN VEZ DE EXIT SE PUEDE UTILIZAR GOTO Y LA ETIQUETA
DECLARE
  I INTEGER:=0;
BEGIN
  LOOP
    IF (I>=10) THEN
      GOTO ETIQUETA_1;
    END IF; 
    DBMS_OUTPUT.PUT_LINE('I:'||I);
    I:=I+1;
    --EXIT WHEN CONDICION;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('ANTES DE ETIQUETA 1');
  <<ETIQUETA_1>>
  DBMS_OUTPUT.PUT_LINE('DESPUES DE ETIQUETA 1');
END;


DECLARE 
  V_NOMBRE HR.EMPLOYEES.FIRST_NAME%TYPE;
  V_APELLIDO HR.EMPLOYEES.LAST_NAME%TYPE;
BEGIN
  SELECT FIRST_NAME, LAST_NAME INTO V_NOMBRE, V_APELLIDO
  FROM HR.EMPLOYEES
  WHERE EMPLOYEE_ID = 100;
  
  DBMS_OUTPUT.PUT_LINE('NOMBRE COMPLETO: ' ||V_NOMBRE||' '||V_APELLIDO);
END;


DECLARE 
  TYPE PERSONA IS RECORD (
      NOMBRE VARCHAR2(200),
      APELLIDO VARCHAR2(200)
  );
  
  V_PERSONA PERSONA;
BEGIN
  V_PERSONA.NOMBRE := 'JUAN';
  V_PERSONA.APELLIDO := 'PEREZ';
  
  DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_PERSONA.NOMBRE||' '||V_PERSONA.APELLIDO);
END;



DECLARE 
  V_REGISTRO HR.EMPLOYEES%ROWTYPE;
BEGIN
  SELECT  EMPLOYEE_ID,
          FIRST_NAME,
          LAST_NAME,
          EMAIL,
          PHONE_NUMBER,
          HIRE_DATE,
          JOB_ID,
          SALARY,
          COMMISSION_PCT,
          MANAGER_ID,
          DEPARTMENT_ID
  INTO V_REGISTRO
  FROM HR.EMPLOYEES
  WHERE EMPLOYEE_ID = 100;
  
  DBMS_OUTPUT.PUT_LINE('NOMBRE COMPLETO: ' ||
        V_REGISTRO.FIRST_NAME||' '||
        V_REGISTRO.LAST_NAME||' ('||
        V_REGISTRO.SALARY||')');
END;