CREATE OR REPLACE PROCEDURE SP_INSERTAR_DETALLE_FAC(
    P_CODIGO_FACTURA INTEGER,
    P_CODIGO_VUELO INTEGER,
    P_CODIGO_PASAJERO INTEGER,
    P_CODIGO_ASIENTO INTEGER,
    P_TICKET VARCHAR2,
    P_COSTO_TICKET NUMBER,
    P_DESCUENTO NUMBER,
    P_MENSAJE OUT VARCHAR2
) AS
  V_CANTIDAD_FACTURAS INTEGER;
  V_CANTIDAD_VUELOS INTEGER;
  V_CANTIDAD_PASAJEROS INTEGER;
  V_CANTIDAD_ASIENTOS INTEGER;
  V_ASIENTO_OCUPADO INTEGER;
BEGIN
  --VERIFICAR SI LA FACTURA EXISTE.
  SELECT COUNT(*)
  INTO V_CANTIDAD_FACTURAS
  FROM TBL_FACTURAS
  WHERE CODIGO_FACTURA = P_CODIGO_FACTURA;
  
  IF (V_CANTIDAD_FACTURAS!=1) THEN
    P_MENSAJE := 'NO EXISTE UNA FACTURA CON CODIGO: '||P_CODIGO_FACTURA;
    RETURN;--SALE DEL PROCEDIMIENTO ALMACENADO
  END IF;
  
  SELECT COUNT(*)
  INTO V_CANTIDAD_VUELOS
  FROM TBL_VUELOS
  WHERE CODIGO_VUELO = P_CODIGO_VUELO;

  IF (V_CANTIDAD_VUELOS!=1) THEN
    P_MENSAJE := 'NO EXISTE EL VUELO CON CODIGO: '||P_CODIGO_VUELO;
    RETURN;
  END IF;
  
  SELECT COUNT(*)
  INTO V_CANTIDAD_PASAJEROS
  FROM TBL_PASAJEROS
  WHERE CODIGO_PASAJERO = P_CODIGO_PASAJERO;
  
  IF (V_CANTIDAD_PASAJEROS!=1) THEN
    P_MENSAJE := 'ERROR, NO EXISTE EL PASAJERO CON CODIGO'||P_CODIGO_PASAJERO;
    RETURN;
  END IF;
  
  SELECT COUNT(*)
  INTO V_CANTIDAD_ASIENTOS
  FROM TBL_ASIENTOS
  WHERE CODIGO_ASIENTO = P_CODIGO_ASIENTO;
  
  IF (V_CANTIDAD_ASIENTOS!=1) THEN
    P_MENSAJE := 'ERROR, NO EXISTE EL ASIENTO CON CODIGO'||P_CODIGO_ASIENTO;
    RETURN;
  END IF;
  
  SELECT COUNT(*)
  INTO V_ASIENTO_OCUPADO
  FROM TBL_FACTURA_DETALLE
  WHERE CODIGO_VUELO = P_CODIGO_VUELO
  AND   CODIGO_ASIENTO = P_CODIGO_ASIENTO;

  IF (V_ASIENTO_OCUPADO=1) THEN
    P_MENSAJE:= 'EL ASIENTO '||P_CODIGO_ASIENTO||' NO ESTA DISPONIBLE.' ;
    RETURN;
  END IF;
  
  INSERT INTO TBL_FACTURA_DETALLE
  (
    CODIGO_FACTURA,
    CODIGO_VUELO,
    CODIGO_PASAJERO,
    CODIGO_ASIENTO,
    TICKET,
    COSTO_TICKET,
    DESCUENTO
  )
  VALUES
  (
    P_CODIGO_FACTURA,
    P_CODIGO_VUELO,
    P_CODIGO_PASAJERO,
    P_CODIGO_ASIENTO,
    P_TICKET,
    P_COSTO_TICKET,
    P_DESCUENTO
  );
  COMMIT;
  P_MENSAJE:='EL REGISTRO SE ALMACENO CON EXITO.';
EXCEPTION
WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLCODE||SQLERRM);
  ROLLBACK;
END;



---ejecutar procedimiento
DECLARE
  V_MENSAJE VARCHAR2(4000);
BEGIN
  SP_INSERTAR_DETALLE_FAC(
      P_CODIGO_FACTURA => 1,
      P_CODIGO_VUELO => 2,
      P_CODIGO_PASAJERO => 1,
      P_CODIGO_ASIENTO => 1,
      P_TICKET =>'ABFFF',
      P_COSTO_TICKET =>500,
      P_DESCUENTO =>20,
      P_MENSAJE => V_MENSAJE
  );
  DBMS_OUTPUT.PUT_LINE(V_MENSAJE);
END;