CREATE TABLE EMPLOYEES_BAJA AS
SELECT * 
FROM EMPLOYEES;
TRUNCATE TABLE EMPLOYEES_BAJA;

SELECT *
FROM EMPLOYEES_BAJA;


CREATE OR REPLACE TRIGGER TRG_EMPLEADOS_BAJA 
AFTER DELETE 
ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEES_BAJA
  (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID,
    FECHA_BAJA
  )
  VALUES
  (
    :OLD.EMPLOYEE_ID,
    :OLD.FIRST_NAME,
    :OLD.LAST_NAME,
    :OLD.EMAIL,
    :OLD.PHONE_NUMBER,
    :OLD.HIRE_DATE,
    :OLD.JOB_ID,
    :OLD.SALARY,
    :OLD.COMMISSION_PCT,
    :OLD.MANAGER_ID,
    :OLD.DEPARTMENT_ID,
    SYSDATE
  );
  COMMIT;
EXCEPTION 
WHEN OTHERS THEN 
  DBMS_OUTPUT.PUT_LINE('ERROR:'||SQLERRM);
END;


SELECT A.*,TO_CHAR(FECHA_BAJA,'DD/MM/YYYY HH:MI:SS') FECHA_HORA
FROM EMPLOYEES_BAJA A;

--52,000
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = :NEW.DEPARTMENT_ID;


CREATE OR REPLACE TRIGGER TRG_VERIFICAR_SALARIO 
BEFORE INSERT OR UPDATE
ON EMPLOYEES 
FOR EACH ROW
DECLARE 
  V_SALARY NUMBER;
BEGIN
  SELECT SUM(SALARY) INTO V_SALARY
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = :NEW.DEPARTMENT_ID;
  
  IF INSERTING THEN
    /*:NEW.SALARY -> Un salario de un empleado
    V_SALARY -> Salario total antes de el insert*/
    IF ((V_SALARY+:NEW.SALARY)>=52000) THEN
      RAISE_APPLICATION_ERROR(-1111,'(INSERT) EL SALARIO SUPERA LOS 52MIL DOLARES');
    END IF;
  ELSIF UPDATING THEN
    IF ((V_SALARY-:OLD.SALARY+:NEW.SALARY)>=52000) THEN
      RAISE_APPLICATION_ERROR(-1111,'(UPDATE) EL SALARIO SUPERA LOS 52MIL DOLARES');
    END IF;
  END IF;
END;

--INTENTAR INSETAR UN REGISTRO PARA QUE UN DEPARTAMENTO
--SUPERE LOS 52MIL
INSERT
INTO EMPLOYEES
  (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
  )
  VALUES
  (
    777,
    'MARIO',
    'LOPEZ',
    'mario@gmail.com',
    '123.123.123',
    sysdate,
    'PU_MAN',
    100,
    0.4,
    null,
    100
);
COMMIT;