--Sentencia Merge Into:
--Sintaxis:

--UPSERT DEL
MERGE INTO <NOMBRE_TABLA>
USING (CONSULTA)
ON (CONDICION)
WHEN MATCHED THEN
  <INSTRUCCION>
WHEN NOT MATCHED THEN
  <INSTRUCCION>;

CREATE TABLE EMPLOYEES_BACKUP AS
SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES_BACKUP;


MERGE INTO EMPLOYEES_BACKUP A
USING (
  SELECT EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
  FROM EMPLOYEES
) B
ON (A.EMPLOYEE_ID = B.EMPLOYEE_ID)
WHEN MATCHED THEN
  UPDATE SET
    A.FIRST_NAME = B.FIRST_NAME,
    A.LAST_NAME = B.LAST_NAME,
    A.EMAIL = B.EMAIL,
    A.PHONE_NUMBER = B.PHONE_NUMBER,
    A.HIRE_DATE = B.HIRE_DATE,
    A.JOB_ID = B.JOB_ID,
    A.SALARY = B.SALARY,
    A.COMMISSION_PCT = B.COMMISSION_PCT,
    A.MANAGER_ID = B.MANAGER_ID,
    A.DEPARTMENT_ID = B.DEPARTMENT_ID
WHEN NOT MATCHED THEN
  INSERT (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID)
  VALUES (
      B.EMPLOYEE_ID,
      B.FIRST_NAME,
      B.LAST_NAME,
      B.EMAIL,
      B.PHONE_NUMBER,
      B.HIRE_DATE,
      B.JOB_ID,
      B.SALARY,
      B.COMMISSION_PCT,
      B.MANAGER_ID,
      B.DEPARTMENT_ID
    );
    
COMMIT;


TRUNCATE TABLE EMPLOYEES_BACKUP;
INSERT INTO EMPLOYEES_BACKUP
SELECT * FROM EMPLOYEES;

COMMIT;
