CREATE OR REPLACE TRIGGER TRG_VERIFICAR_USUARIO 
BEFORE
INSERT ON TBL_TABLERO
FOR EACH ROW
DECLARE
  V_CANTIDAD_USUARIOS INTEGER;
  V_CANTIDAD_TABLEROS INTEGER;
BEGIN
  SELECT COUNT(*)
  INTO V_CANTIDAD_USUARIOS
  FROM TBL_USUARIOS_X_ORGANIZACION
  WHERE CODIGO_USUARIO = :NEW.CODIGO_USUARIO_CREA
  AND   CODIGO_ORGANIZACION = :NEW.CODIGO_ORGANIZACION;
  DBMS_OUTPUT.PUT_LINE('CANTIDAD: '||V_CANTIDAD_USUARIOS);
  
  IF (V_CANTIDAD_USUARIOS<=0) THEN
      raise_application_error(-20600, 'El usuario no esta registrado en dicha organizacion.');
  END IF;
  SELECT COUNT(*)
  INTO V_CANTIDAD_TABLEROS
  FROM TBL_TABLERO
  WHERE UPPER(TRIM(NOMBRE_TABLERO)) = UPPER(TRIM(:NEW.NOMBRE_TABLERO));
  IF (V_CANTIDAD_TABLEROS>=1) THEN
    raise_application_error(-20600, 'Ya existe un tablero con el mismo nombre.');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM||'('||SQLCODE||')');
END;
