SELECT *
FROM TBL_TARJETAS;

SELECT COUNT(1)
FROM TBL_LISTAS A
INNER JOIN TBL_TABLERO B
ON (A.CODIGO_TABLERO = B.CODIGO_TABLERO)
INNER JOIN TBL_USUARIOS_X_ORGANIZACION C
ON (B.CODIGO_ORGANIZACION = C.CODIGO_ORGANIZACION)
WHERE CODIGO_LISTA = 1;

SELECT *
FROM TBL_TABLERO;

SELECT *
FROM TBL_USUARIOS_X_ORGANIZACION;


CREATE OR REPLACE TRIGGER TRGR_VERIFICAR_USUARIO_2 
BEFORE 
INSERT ON TBL_TARJETAS
FOR EACH ROW
DECLARE
  V_CANTIDAD_REGISTROS INTEGER;
BEGIN
  SELECT COUNT(1)
  INTO V_CANTIDAD_REGISTROS
  FROM TBL_LISTAS A
  INNER JOIN TBL_TABLERO B
  ON (A.CODIGO_TABLERO = B.CODIGO_TABLERO)
  INNER JOIN TBL_USUARIOS_X_ORGANIZACION C
  ON (B.CODIGO_ORGANIZACION = C.CODIGO_ORGANIZACION)
  WHERE CODIGO_LISTA = :NEW.CODIGO_LISTA
  AND CODIGO_USUARIO = :NEW.CODIGO_USUARIO;
  
  IF (V_CANTIDAD_REGISTROS <=0 ) THEN
    raise_application_error(-20600, 'El usuario no esta en la organizacion.');
  END IF;
END;


INSERT
INTO TBL_TARJETAS
  (
    CODIGO_TARJETA,
    TITULO_TARJETA,
    DESCRIPCION,
    FECHA_CREACION,
    FECHA_LIMITE,
    CODIGO_LISTA,
    CODIGO_USUARIO
  )
  VALUES
  (
    9999999,
    'TARJETA PRUEBA',
    'TARJETA PRUEBA',
    SYSDATE,
    SYSDATE + 100,
    10,
    252
  );

SELECT *
FROM TBL_TARJETAS
WHERE CODIGO_TARJETA = 9999999;


COMMIT;

SELECT *
FROM TBL_LISTAS
WHERE CODIGO_LISTA = 10;

SELECT *
FROM TBL_TABLERO
WHERE CODIGO_TABLERO = 22;

SELECT *
FROM TBL_USUARIOS
WHERE CODIGO_USUARIO = 252;

SELECT *
FROM TBL_USUARIOS_X_ORGANIZACION
WHERE CODIGO_USUARIO = 252;
--18






SELECT *
FROM ALL_TABLES
WHERE OWNER = 'HR';

SELECT *
FROM ALL_PROCEDURES
WHERE OWNER = 'HR';


--F_EXISTE_OBJETO('HR','EMPLOYEES','TABLE');


CREATE OR REPLACE PACKAGE PKG_EXAMEN AS
  FUNCTION F_EXISTE_OBJETO(P_ESQUEMA VARCHAR2, P_OBJETO VARCHAR2, P_TIPO VARCHAR2) RETURN BOOLEAN;
END;


CREATE OR REPLACE PACKAGE BODY PKG_EXAMEN AS 
  FUNCTION F_EXISTE_OBJETO(P_ESQUEMA VARCHAR2, P_OBJETO VARCHAR2, P_TIPO VARCHAR2) 
  RETURN BOOLEAN 
  AS
    V_CANTIDAD_REGISTROS INTEGER:=0;
  BEGIN
    CASE 
      WHEN P_TIPO = 'TABLE' THEN
        SELECT COUNT(1)
        INTO V_CANTIDAD_REGISTROS
        FROM ALL_TABLES
        WHERE OWNER = P_ESQUEMA
        AND TABLE_NAME = P_OBJETO;
      END;
      WHEN P_TIPO IN ('PROCEDURE', 'FUNCTION', 'PACKAGE') THEN
        SELECT COUNT(1)
        INTO V_CANTIDAD_REGISTROS
        FROM ALL_PROCEDURES
        WHERE OWNER = P_ESQUEMA
        AND OBJECT_TYPE = P_TIPO
        AND PROCEDURE_NAME = P_OBJETO;
      END;
    END CASE;
    IF (V_CANTIDAD_REGISTROS>=1) THEN
      RETURN TRUE;
    ELSE
      RETURN FALSE;
    END IF;
  END F_EXISTE_OBJETO;
END PKG_EXAMEN;


SET SERVEROUTPUT ON;
BEGIN
  IF (PKG_EXAMEN.F_EXISTE_OBJETO('TRELLO','F_EXISTE_OBJETO','PACKAGE')) THEN
    DBMS_OUTPUT.PUT_LINE('CLARO QUE EXISTE');
  ELSE
    DBMS_OUTPUT.PUT_LINE('NO EXISTE');
  END IF;
END;



SELECT *
FROM ALL_PROCEDURES
WHERE PROCEDURE_NAME = 'F_EXISTE_OBJETO';